import re
import os
from dotenv import load_dotenv
from openai import OpenAI
import httpx
from policy_agent.policy_analysis.regal.regal_finder import create_regal_suggestion
load_dotenv()

def regal_update(api_key, openai_base_url, policy_dir, policy_path, regal_suggestion_path, MODEL, regal_result_output, modified_policy_regal, temp, top_p):

    create_regal_suggestion(policy_dir, regal_suggestion_path)
    
    http_client = httpx.Client(
        verify=False,    
        timeout=300.0      
    )

    client = OpenAI(
        api_key=api_key,
        base_url=openai_base_url,
        http_client=http_client 
    )
    
    regal_feedback=''
    rego_policy=''
    if not os.path.exists(policy_path):
        raise FileNotFoundError(f"Missing {policy_path}")

    with open(policy_path, "r", encoding="utf-8") as f:
        rego_policy = f.read()

    with open(regal_suggestion_path, "r", encoding="utf-8") as f:
        regal_feedback = f.read()

    system_instruction = """
    You are a code assistant specialized in analyzing Open Policy Agent (OPA) Rego policies.

    You are given:
    1. A set of suggestions generated by regal paired with the link of its documentation.
    2. The full Rego policy source code governing kubectl operations.

    # Task
    Analyze the policy and suggestions to:
    - Search the attached documnet link to understand each suggestion.
    - Update the policy following the explaination in the document and suggestions if necessary, please refer to the document to understand how to solve the suggestion, if you are unsure, do not fix it.
    - Apply minimal and localized edits to strengthen the policy.
    - Modify existing rules where possible instead of adding new ones.
    - Ensure legitimate kubectl usage is not over-restricted.

    # Constraints
    - Do NOT rewrite or refactor the entire policy.
    - Keep rule names, structure, and logic consistent.
    - Add only narrowly scoped conditions to block the bypasses.
    - Maintain the existing allow/deny semantics and namespace checks.

    # Output Format
    1. A detailed analysis section for each suggestion.
    2. At the end, include the **complete modified Rego policy** in this format:

    ```rego
    <updated policy here>
    """

    user_prompt = f"""
    Regal suggestions
    {regal_feedback}
    Current Rego Policy
    {rego_policy}
    Instructions
    Analyze how each suggestion can improve the policy and return the updated Rego code that improves the policy following these suggestions.
    """

    print("Analyzing and strengthening the OPA policy...")
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": user_prompt},
        ],
        max_tokens=30000,
        temperature=temp, 
        top_p=top_p
    )


    assistant_output = response.choices[0].message.content


    with open(regal_result_output, "w", encoding="utf-8") as f:
        f.write(assistant_output)
    print(f"Full analysis saved to: {regal_result_output}")

    def extract_rego_block(text: str):
        match = re.search(r"```(?:rego)?\s*(.*?)```", text, re.S | re.I)
        if match:
            return match.group(match.lastindex).strip()

        match2 = re.search(r"(package\s+[\s\S]+)$", text, re.I)
        if match2:
            return match2.group(match.lastindex).strip()

        return None


    rego_block = extract_rego_block(assistant_output)

    if rego_block:
        with open(modified_policy_regal, "w", encoding="utf-8") as f:
            f.write(rego_block)
        with open(policy_path, "w", encoding="utf-8") as f:
            f.write(rego_block)
        print(f"Modified Rego policy copy saved to: {modified_policy_regal}")
    else:
        print("No Rego code block detected — please check analysis_notes.txt manually.")

    print("Done.")